# Generated by Django 6.0 on 2026-02-05 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0003_normalize_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Profile",
                "verbose_name_plural": "Role Profiles",
            },
        ),
    ]
