# Generated by Django 6.0 on 2026-02-05 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0003_boarditem_boardlink_captaindecision_complaint_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.BigIntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("bail", "Bail"),
                            ("fine", "Fine"),
                            ("reward", "Reward"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("gateway_reference", models.CharField(blank=True, max_length=100)),
                ("callback_payload", models.JSONField(blank=True, default=dict)),
                ("return_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cases.case",
                    ),
                ),
                (
                    "suspect_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cases.suspectcaseprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RewardReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("officer_review", "Officer Review"),
                            ("detective_review", "Detective Review"),
                            ("rejected", "Rejected"),
                            ("approved", "Approved"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                (
                    "unique_code",
                    models.CharField(blank=True, max_length=24, unique=True),
                ),
                ("reward_amount", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cases.case",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reward_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by_detective",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detective_reward_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="officer_reward_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suspect_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cases.suspectcaseprofile",
                    ),
                ),
            ],
        ),
    ]
