# Generated by Django 5.1 on 2026-02-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_rewardreport_assigned_detective"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rewardreport",
            name="unique_code",
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
