# Generated by Django 6.0 on 2026-02-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("Complaint", "Complaint"),
                            ("CrimeScene", "Crime Scene Report"),
                        ],
                        default="Complaint",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("PendingCadet", "Pending Cadet Review"),
                            ("NeedsComplainantUpdate", "Needs Complainant Update"),
                            ("PendingOfficer", "Pending Officer Review"),
                            ("Open", "Open / Investigating"),
                            ("WarrantPending", "Warrant Requested"),
                            ("InCourt", "Sent to Court"),
                            ("Closed", "Case Closed"),
                            ("Void", "Void (3 Strikes)"),
                        ],
                        default="Draft",
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(
                        choices=[
                            (1, "Level 3 (Petty)"),
                            (2, "Level 2 (Grand Theft)"),
                            (3, "Level 1 (Murder)"),
                            (4, "Critical (Terror/Serial)"),
                        ],
                        default=1,
                    ),
                ),
                ("rejection_count", models.PositiveSmallIntegerField(default=0)),
                ("crime_scene_datetime", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_verify_complaint", "Can verify initial complaint (Cadet)"),
                    ("can_approve_case", "Can approve case creation (Officer)"),
                    ("can_issue_warrant", "Can issue arrest warrant (Sergeant)"),
                    ("can_close_case", "Can close the case (Captain/Chief)"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CaseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CaseReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("Cadet", "Cadet Review"),
                            ("Officer", "Officer Review"),
                            ("Supervisor", "Supervisor Review"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("Approve", "Approve"),
                            ("Reject", "Reject"),
                            ("ReturnForFix", "Return For Fix"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
