# Generated by Django 6.0 on 2026-02-05 06:10

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("evidence", "Evidence"),
                            ("witness", "Witness"),
                            ("suspect", "Suspect"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note_text", models.TextField(blank=True)),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("width", models.FloatField(default=300)),
                ("height", models.FloatField(default=160)),
            ],
        ),
        migrations.CreateModel(
            name="BoardLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="CaptainDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
                ("chief_confirmed", models.BooleanField(blank=True, null=True)),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("incident_datetime", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("returned", "Returned"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("void", "Void"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("invalid_attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[("cadet", "Cadet"), ("officer", "Officer")],
                        max_length=20,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("returned", "Returned"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectiveBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InterrogationScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scorer_role",
                    models.CharField(
                        choices=[("detective", "Detective"), ("sergeant", "Sergeant")],
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SuspectCaseProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wanted_since", models.DateTimeField(auto_now_add=True)),
                ("arrest_warrant_issued", models.BooleanField(default=False)),
                ("is_arrested", models.BooleanField(default=False)),
                ("severe_tracking", models.BooleanField(default=False)),
                ("public_photo", models.URLField(blank=True)),
                ("public_details", models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="casereview",
            name="case",
        ),
        migrations.RemoveField(
            model_name="casereview",
            name="reviewer",
        ),
        migrations.RemoveField(
            model_name="case",
            name="crime_scene_datetime",
        ),
        migrations.RemoveField(
            model_name="case",
            name="rejection_count",
        ),
        migrations.AddField(
            model_name="case",
            name="incident_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="case",
            name="suspects",
            field=models.ManyToManyField(
                blank=True, related_name="suspect_cases", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="witnesses",
            field=models.ManyToManyField(
                blank=True, related_name="witness_cases", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="complainants",
            field=models.ManyToManyField(
                blank=True, related_name="complaint_cases", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="severity",
            field=models.IntegerField(
                choices=[
                    (1, "Level 3 (Petty)"),
                    (2, "Level 2"),
                    (3, "Level 1"),
                    (4, "Critical"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("PendingCadet", "Pending Cadet Review"),
                    ("NeedsComplainantUpdate", "Needs Complainant Update"),
                    ("PendingOfficer", "Pending Officer Review"),
                    ("Open", "Open / Investigating"),
                    ("WarrantPending", "Warrant Requested"),
                    ("Arrested", "Suspect Arrested"),
                    ("InCourt", "Sent to Court"),
                    ("Closed", "Case Closed"),
                    ("Void", "Void"),
                ],
                default="Draft",
                max_length=32,
            ),
        ),
    ]
