# Generated by Django 6.0 on 2026-02-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_boarditem_evidence_boarditem_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interrogationscore",
            name="scorer_role",
            field=models.CharField(
                choices=[
                    ("detective", "Detective"),
                    ("sergeant", "Sergeant"),
                ],
                max_length=20,
            ),
        ),
    ]
