# Generated by Django 5.1 on 2026-02-15 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0007_crimescenewitness_secondarycomplainant"),
        ("evidence", "0003_biomedicalevidence_validation_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("PendingCadet", "Pending Cadet Review"),
                    ("NeedsComplainantUpdate", "Needs Complainant Update"),
                    ("PendingOfficer", "Pending Officer Review"),
                    ("Open", "Open / Investigating"),
                    ("WarrantPending", "Warrant Requested"),
                    ("Arrested", "Suspect Arrested"),
                    ("WaitingCaptain", "Waiting For Captain Decision"),
                    ("WaitingChief", "Waiting For Chief Confirmation"),
                    ("InCourt", "Sent to Court"),
                    ("Closed", "Case Closed"),
                    ("Void", "Void"),
                ],
                default="Draft",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ComplaintAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="complaints/attachments/%Y/%m/")),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="cases.complaint",
                    ),
                ),
                (
                    "promoted_evidence",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_complaint_attachment",
                        to="evidence.evidence",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_complaint_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
