# Generated by Django 5.1 on 2026-02-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_crimescenewitness_secondarycomplainant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('PendingCadet', 'Pending Cadet Review'), ('NeedsComplainantUpdate', 'Needs Complainant Update'), ('PendingOfficer', 'Pending Officer Review'), ('Open', 'Open / Investigating'), ('WarrantPending', 'Warrant Requested'), ('Arrested', 'Suspect Arrested'), ('WaitingCaptain', 'Waiting For Captain Decision'), ('WaitingChief', 'Waiting For Chief Confirmation'), ('InCourt', 'Sent to Court'), ('Closed', 'Case Closed'), ('Void', 'Void')], default='Draft', max_length=32),
        ),
    ]
