# Generated by Django 5.1 on 2026-02-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspectcaseprofile',
            name='bail_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspectcaseprofile',
            name='is_bail_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
