# Generated by Django 6.0 on 2026-02-05 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_alter_interrogationscore_scorer_role"),
        ("judiciary", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trial",
            name="defendant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="defendant_trials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trial",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trials",
                to="cases.case",
            ),
        ),
        migrations.AlterField(
            model_name="trial",
            name="verdict",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("innocent", "Innocent"),
                    ("guilty", "Guilty"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
