# Generated by Django 6.0 on 2026-02-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizentip",
            name="status",
            field=models.CharField(
                choices=[
                    ("officer_review", "Officer Review"),
                    ("detective_review", "Detective Review"),
                    ("approved", "Approved"),
                ],
                default="officer_review",
                max_length=30,
            ),
        ),
    ]
