# Generated by Django 5.1 on 2026-02-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_citizentip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizentip',
            name='status',
            field=models.CharField(choices=[('officer_review', 'Officer Review'), ('detective_review', 'Detective Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='officer_review', max_length=30),
        ),
    ]
