# Generated by Django 5.1 on 2026-02-21 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_biomedicalevidence_validation_status_and_more'),
        ('people', '0003_alter_citizentip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizentip',
            name='linked_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizen_tip_links', to='evidence.evidence'),
        ),
        migrations.AddField(
            model_name='citizentip',
            name='reward_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='citizentip',
            name='unique_tracking_code',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='citizentip',
            name='useful_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citizentip',
            name='status',
            field=models.CharField(choices=[('officer_review', 'Officer Review'), ('detective_review', 'Detective Review'), ('useful', 'Useful'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='officer_review', max_length=30),
        ),
    ]
