# Generated by Django 6.0 on 2026-02-05 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0003_boarditem_boardlink_captaindecision_complaint_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BioMedicalEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_followup", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="BioMedicalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_file", models.FileField(upload_to="evidence/biomedical/")),
                (
                    "bio_medical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="evidence.biomedicalevidence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("transcription", "Transcription"),
                            ("bio_medical", "Bio/Medical"),
                            ("vehicle", "Vehicle"),
                            ("identity_document", "Identity Document"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="biomedicalevidence",
            name="evidence",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bio_medical",
                to="evidence.evidence",
            ),
        ),
        migrations.CreateModel(
            name="IdentityDocumentEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_full_name", models.CharField(max_length=255)),
                (
                    "evidence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_document",
                        to="evidence.evidence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranscriptionEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transcript_text", models.TextField()),
                (
                    "evidence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcription",
                        to="evidence.evidence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranscriptionMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_file", models.FileField(upload_to="evidence/transcription/")),
                (
                    "transcription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="evidence.transcriptionevidence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=128)),
                ("color", models.CharField(max_length=64)),
                ("license_plate", models.CharField(blank=True, max_length=20)),
                ("serial_number", models.CharField(blank=True, max_length=50)),
                (
                    "evidence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle",
                        to="evidence.evidence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdentityDocumentField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField(blank=True)),
                (
                    "identity_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="evidence.identitydocumentevidence",
                    ),
                ),
            ],
            options={
                "unique_together": {("identity_document", "key")},
            },
        ),
    ]
