# Generated by Django 5.1 on 2026-02-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_biomedicalevidence_lab_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomedicalevidence',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
