from django.urls import path

from .views import (
    AggregatedStatsAPIView,
    BoardItemListCreateAPIView,
    BoardItemRetrieveUpdateDestroyAPIView,
    BoardLinkDestroyAPIView,
    BoardLinkListCreateAPIView,
    BoardConnectionDestroyAPIView,
    BoardConnectionListCreateAPIView,
    CaptainDecisionCreateAPIView,
    CaseBreakdownStatsAPIView,
    CaseListCreateAPIView,
    CaseClaimAPIView,
    CaseRetrieveUpdateAPIView,
    ChiefDecisionAPIView,
    ComplaintAddComplainantsAPIView,
    ComplaintCadetReviewAPIView,
    ComplaintListCreateAPIView,
    ComplaintOfficerReviewAPIView,
    ComplaintSecondaryComplainantListAPIView,
    ComplaintSecondaryComplainantRequestAPIView,
    ComplaintSecondaryComplainantReviewAPIView,
    ComplaintRetrieveUpdateAPIView,
    CrimeSceneCaseApproveAPIView,
    CrimeSceneCaseCreateAPIView,
    DetectiveBoardDetailAPIView,
    DetectiveNotificationListAPIView,
    InterrogationScoreCreateAPIView,
    SergeantDecisionAPIView,
    SergeantSubmitToCaptainAPIView,
    UnassignedCaseListAPIView,
    SuspectProfileListAPIView,
    SuspectBailPolicyUpdateAPIView,
    SevereTrackingListAPIView,
    SuspectArrestAPIView,
    SuspectNominationAPIView,
    SuspectWantedUpdateAPIView,
)

urlpatterns = [
    path("", CaseListCreateAPIView.as_view(), name="case-list-create"),
    path("unassigned/", UnassignedCaseListAPIView.as_view(), name="case-unassigned-list"),
    path("<int:case_id>/claim/", CaseClaimAPIView.as_view(), name="case-claim"),
    path("<int:pk>/", CaseRetrieveUpdateAPIView.as_view(), name="case-detail-update"),

    path("complaints/", ComplaintListCreateAPIView.as_view(), name="complaint-list-create"),
    path("complaints/<int:pk>/", ComplaintRetrieveUpdateAPIView.as_view(), name="complaint-detail-update"),
    path("complaints/<int:complaint_id>/add-complainants/", ComplaintAddComplainantsAPIView.as_view(), name="complaint-add-complainants"),
    path(
        "complaints/<int:complaint_id>/secondary-complainants/",
        ComplaintSecondaryComplainantListAPIView.as_view(),
        name="complaint-secondary-complainants",
    ),
    path(
        "complaints/<int:complaint_id>/secondary-complainants/request/",
        ComplaintSecondaryComplainantRequestAPIView.as_view(),
        name="complaint-secondary-complainants-request",
    ),
    path(
        "complaints/<int:complaint_id>/secondary-complainants/<int:entry_id>/review/",
        ComplaintSecondaryComplainantReviewAPIView.as_view(),
        name="complaint-secondary-complainants-review",
    ),
    path("complaints/<int:complaint_id>/cadet-review/", ComplaintCadetReviewAPIView.as_view(), name="complaint-cadet-review"),
    path("complaints/<int:complaint_id>/officer-review/", ComplaintOfficerReviewAPIView.as_view(), name="complaint-officer-review"),

    path("crime-scene-reports/", CrimeSceneCaseCreateAPIView.as_view(), name="crime-scene-create"),
    path("<int:case_id>/crime-scene-approve/", CrimeSceneCaseApproveAPIView.as_view(), name="crime-scene-approve"),

    path("<int:case_id>/board/", DetectiveBoardDetailAPIView.as_view(), name="detective-board"),
    path("<int:case_id>/board/items/", BoardItemListCreateAPIView.as_view(), name="board-item-list-create"),
    path("board/items/<int:pk>/", BoardItemRetrieveUpdateDestroyAPIView.as_view(), name="board-item-rud"),
    path("<int:case_id>/board/links/", BoardLinkListCreateAPIView.as_view(), name="board-link-list-create"),
    path("board/links/<int:pk>/", BoardLinkDestroyAPIView.as_view(), name="board-link-delete"),
    path("<int:case_id>/board/connections/", BoardConnectionListCreateAPIView.as_view(), name="board-connection-list-create"),
    path("board/connections/<int:pk>/", BoardConnectionDestroyAPIView.as_view(), name="board-connection-delete"),

    path("<int:case_id>/suspects/nominate/", SuspectNominationAPIView.as_view(), name="suspects-nominate"),
    path("<int:case_id>/suspects/sergeant-decision/", SergeantDecisionAPIView.as_view(), name="sergeant-decision"),
    path("suspect-profiles/<int:profile_id>/arrest/", SuspectArrestAPIView.as_view(), name="suspect-arrest"),
    path("suspect-profiles/<int:profile_id>/score/", InterrogationScoreCreateAPIView.as_view(), name="suspect-score"),
    path("suspect-profiles/<int:profile_id>/bail-policy/", SuspectBailPolicyUpdateAPIView.as_view(), name="suspect-bail-policy"),
    path("suspect-profiles/", SuspectProfileListAPIView.as_view(), name="suspect-profile-list"),
    path("suspect-profiles/<int:profile_id>/captain-decision/", CaptainDecisionCreateAPIView.as_view(), name="captain-decision"),
    path("<int:case_id>/submit-to-captain/", SergeantSubmitToCaptainAPIView.as_view(), name="submit-to-captain"),
    path("captain-decisions/<int:decision_id>/chief-decision/", ChiefDecisionAPIView.as_view(), name="chief-decision"),
    path("suspect-profiles/<int:profile_id>/wanted/", SuspectWantedUpdateAPIView.as_view(), name="suspect-wanted-update"),

    path("notifications/detective/", DetectiveNotificationListAPIView.as_view(), name="detective-notifications"),
    path("wanted/severe-tracking/", SevereTrackingListAPIView.as_view(), name="severe-tracking-list"),

    path("stats/aggregated/", AggregatedStatsAPIView.as_view(), name="aggregated-stats"),
    path("stats/breakdown/", CaseBreakdownStatsAPIView.as_view(), name="case-breakdown-stats"),
]
